---
name: Clang-tidy

on: [push, pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get -y install libboost-dev libboost-test-dev

    - name: Run clang-tidy
      run: |
        clang-tidy --version
        cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
        clang-tidy $(find -name *.cpp | grep -v CompilerId) -extra-arg=-std=c++20
