---
name: Test CMake build

on: [push, pull_request]

jobs:
  build:
    name:
      Cmake
    strategy:
      fail-fast: false
      matrix:
        cc:          [gcc, clang]
        cmake_flags: ["-DBUILD_EXAMPLES=ON",
                      "-DUSE_SYSTEM_MINIZIP=ON",
                      ]
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get -y install libboost-dev libboost-test-dev
        sudo apt-get -y install zlib1g-dev
        sudo apt-get -y install libminizip-dev
        sudo apt-get -y install libssl-dev

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_TESTS=ON ${{ matrix.cmake_flags }} -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Test
      run: |
        cd build
        for f in test/unit/*; do ./$f; done
