---
name: Linters

on:
  push:
    branches:
      - main
  pull_request:
permissions: {}

jobs:
  Clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
      with:
        persist-credentials: false

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get -y install libboost-dev libboost-test-dev

    - name: Run clang-tidy
      run: |
        clang-tidy --version
        cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
        clang-tidy $(find -name *.cpp | grep -v CompilerId) -extra-arg=-std=c++20

  Cppcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
      with:
        persist-credentials: false

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get -y install cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --version
        cppcheck . --enable=all --std=c++20  --library=boost --check-level=exhaustive  --error-exitcode=2 -I include -i third_party --force --inline-suppr  \
          --suppress=unusedFunction --suppress=missingIncludeSystem --suppress=checkersReport --suppress=unmatchedSuppression --suppress='*:include/xwpp/third_party/*'
